POST localhost:8080/api/v1/category/create
Content-Type: application/json

{
  "name": "electronic"
}

###
GET localhost:8080/api/v1/category?page=1&size=5


###
PUT localhost:8080/api/v1/category/update/72070588-392c-4ad6-a9c7-958e94b549d7
Content-Type: application/json

{
  "name": "Clothes"
}

###
DELETE localhost:8080/api/v1/category/delete/72070588-392c-4ad6-a9c7-958e94b549d7