###
POST http://localhost:8080/api/v1/photo/upload?productId=d628769f-2e10-4805-b9a1-481d88a88047
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="photo.jpg"

< C:\Users\azizb\Desktop\photo.jpg


###
GET http://localhost:8080/api/v1/photo/a130ac36-e822-492e-9ce0-2d94f49b64b4
