### Post a new product
POST localhost:8080/api/v1/product
Content-Type: application/json

{
  "title": "iPhone 15 pro",
  "description": "Apple phone",
  "price": 1000,
  "sellerId": "f0059075-e2f4-4722-868e-88bd25474fe3",
  "categoryId": "71ae8e8a-2f58-4706-9799-2beb598b3319"
}

### Post a new product
POST localhost:8080/api/v1/product
Content-Type: application/json

{
  "title": "Macbook air 2017",
  "description": "new notebook",
  "price": 2000,
  "categoryId": "71ae8e8a-2f58-4706-9799-2beb598b3319",
  "sellerId": "f0059075-e2f4-4722-868e-88bd25474fe3"
}

### Get all products
GET localhost:8080/api/v1/product/get-all?page=0&size=5

### Get by seller
GET localhost:8080/api/v1/product/get-by-seller/e59922f4-2002-4122-9877-b012eaaaa479?page=0&size=5

### Search by title
GET localhost:8080/api/v1/product/search?title=iPhone&page=0&size=5

### Get by price range
GET localhost:8080/api/v1/product/get-by-range?minPrice=100&maxPrice=2000

### Update product by id
PUT localhost:8080/api/v1/product/e59922f4-2002-4122-9877-b012eaaaa479
Content-Type: application/json

{
  "title": "Mac book",
  "description": "Notebook",
  "price": 1200
}

### Delete product by id
DELETE localhost:8080/api/v1/product/e59922f4-2002-4122-9877-b012eaaaa479