###
POST localhost:8080/api/v1/reviews/create
Content-Type: application/json

{
  "rating": 5,
  "comment": "very good",
  "productId": "51a3cf0e-73ed-4305-9ce7-8edcdf82dfb4"

}


###
GET localhost:8080/api/v1/reviews/get-all-productId?productId=0e617a07-58ca-4eed-adcb-42d955b8bc62


###
GET localhost:8080/api/v1/reviews/get-review/6b1c2240-9d49-465c-a221-0d9faf5a4302


###
PUT localhost:8080/api/v1/reviews/update/review/6b1c2240-9d49-465c-a221-0d9faf5a4302
Content-Type: application/json

{
  "productId": "0e617a07-58ca-4eed-adcb-42d955b8bc6",
  "rating": 4,
  "comment": "Yaxshi, lekin narxi baland."
}
